---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
LIST <- c("http://ja.dbpedia.org/dumps/20210301/article-templates_lang%3Dja_720A.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/article-templates_lang%3Dja_nested_A054.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/categories_lang%3Dja_articles_3B7C.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/categories_lang%3Dja_labels_1F3B.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/categories_lang%3Dja_skos_5075.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/commons-sameas-links_lang%3Dja_EC34.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/disambiguations_lang%3Dja_6B29.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/equations_lang%3Dja_67B2.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/external-links_lang%3Dja_EB09.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/geo-coordinates-mappingbased_lang%3Dja_9AB6.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/geo-coordinates_lang%3Dja_AF3D.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/homepages_lang%3Dja_7E6D.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/infobox-properties_lang%3Dja_85E9.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/infobox-property-definitions_lang%3Dja_F4AF.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/instance-types_lang%3Dja_specific_2919.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/instance-types_lang%3Dja_transitive_BD7F.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/interlanguage-links_lang%3Dja_9C44.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/labels_lang%3Dja_3EB3.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/long-abstracts_lang%3Dja_983C.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/mappingbased-literals_lang%3Dja_5F00.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/mappingbased-objects-uncleaned_lang%3Dja_6079.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/mappingbased-objects_lang%3Dja_6A46.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/mappingbased-objects_lang%3Dja_disjointDomain_8498.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/mappingbased-objects_lang%3Dja_disjointRange_73CC.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/nif-context_lang%3Dja_052B.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/nif-page-structure_lang%3Dja_0723.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/nif-text-links_lang%3Dja_515A.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/page_lang%3Dja_ids_14E8.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/page_lang%3Dja_length_E445.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/raw-tables_lang%3Dja_AECC.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/redirects_lang%3Dja_2B58.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/redirects_lang%3Dja_transitive_2A7A.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/revisions_lang%3Dja_ids_85A9.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/revisions_lang%3Dja_uris_8D96.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/short-abstracts_lang%3Dja_4D0F.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/specific-mappingbased-properties_lang%3Dja_715B.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/topical-concepts_lang%3Dja_3816.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/wikilinks_lang%3Dja_780B.ttl.bz2",
"http://ja.dbpedia.org/dumps/20210301/wikipedia-links_lang%3Dja_6324.ttl.bz2")

head(LIST)

if(T){
proxy_url = "http://wwwproxy.osakac.ac.jp:8080"
Sys.setenv("http_proxy" = proxy_url)
Sys.setenv("https_proxy" = proxy_url)
Sys.setenv("ftp_proxy" = proxy_url)
}

```

```{r}
getwd()
setwd("./AHLodDbs_02_Dataset_v01/jadbpedia/v01_20210301")

for(n in seq_len(length(LIST))){
  system(paste0("wget -b ", LIST[n]))
}

#実行状態
system("ps -A | grep 'wget -b'")

#
a <- dir(pattern = "wget-log")
file.remove(a)


```
